import "./index.css"

export default function Float() {
    return (
        <div id="wd-float-divs">
            <h2>Float</h2>
            <div>
                <img className="wd-float-right"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut malesuada dui. Aenean pharetra pretium vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel diam et enim aliquet ultrices non ac risus. Sed dapibus, risus a mollis imperdiet, ipsum metus ultrices ante, nec cursus nisi metus ac enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus sed eros at maximus. Cras interdum iaculis diam, sollicitudin malesuada odio dignissim non. Nullam quis facilisis velit. Nam sit amet ligula consectetur, volutpat lorem nec, posuere mi. Praesent quis tempor risus, id pulvinar enim. Nulla nisi nunc, lacinia at malesuada et, vulputate a mauris. Etiam tempor volutpat ex. Nam gravida tempor pulvinar.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut malesuada dui. Aenean pharetra pretium vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel diam et enim aliquet ultrices non ac risus. Sed dapibus, risus a mollis imperdiet, ipsum metus ultrices ante, nec cursus nisi metus ac enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus sed eros at maximus. Cras interdum iaculis diam, sollicitudin malesuada odio dignissim non. Nullam quis facilisis velit. Nam sit amet ligula consectetur, volutpat lorem nec, posuere mi. Praesent quis tempor risus, id pulvinar enim. Nulla nisi nunc, lacinia at malesuada et, vulputate a mauris. Etiam tempor volutpat ex. Nam gravida tempor pulvinar.
                <img className="wd-float-left"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut malesuada dui. Aenean pharetra pretium vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel diam et enim aliquet ultrices non ac risus. Sed dapibus, risus a mollis imperdiet, ipsum metus ultrices ante, nec cursus nisi metus ac enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus sed eros at maximus. Cras interdum iaculis diam, sollicitudin malesuada odio dignissim non. Nullam quis facilisis velit. Nam sit amet ligula consectetur, volutpat lorem nec, posuere mi. Praesent quis tempor risus, id pulvinar enim. Nulla nisi nunc, lacinia at malesuada et, vulputate a mauris. Etiam tempor volutpat ex. Nam gravida tempor pulvinar.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut malesuada dui. Aenean pharetra pretium vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel diam et enim aliquet ultrices non ac risus. Sed dapibus, risus a mollis imperdiet, ipsum metus ultrices ante, nec cursus nisi metus ac enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus sed eros at maximus. Cras interdum iaculis diam, sollicitudin malesuada odio dignissim non. Nullam quis facilisis velit. Nam sit amet ligula consectetur, volutpat lorem nec, posuere mi. Praesent quis tempor risus, id pulvinar enim. Nulla nisi nunc, lacinia at malesuada et, vulputate a mauris. Etiam tempor volutpat ex. Nam gravida tempor pulvinar.
                <img className="wd-float-right"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut malesuada dui. Aenean pharetra pretium vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel diam et enim aliquet ultrices non ac risus. Sed dapibus, risus a mollis imperdiet, ipsum metus ultrices ante, nec cursus nisi metus ac enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus sed eros at maximus. Cras interdum iaculis diam, sollicitudin malesuada odio dignissim non. Nullam quis facilisis velit. Nam sit amet ligula consectetur, volutpat lorem nec, posuere mi. Praesent quis tempor risus, id pulvinar enim. Nulla nisi nunc, lacinia at malesuada et, vulputate a mauris. Etiam tempor volutpat ex. Nam gravida tempor pulvinar.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut malesuada dui. Aenean pharetra pretium vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel diam et enim aliquet ultrices non ac risus. Sed dapibus, risus a mollis imperdiet, ipsum metus ultrices ante, nec cursus nisi metus ac enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus sed eros at maximus. Cras interdum iaculis diam, sollicitudin malesuada odio dignissim non. Nullam quis facilisis velit. Nam sit amet ligula consectetur, volutpat lorem nec, posuere mi. Praesent quis tempor risus, id pulvinar enim. Nulla nisi nunc, lacinia at malesuada et, vulputate a mauris. Etiam tempor volutpat ex. Nam gravida tempor pulvinar.
                <img className="wd-float-left"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut malesuada dui. Aenean pharetra pretium vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel diam et enim aliquet ultrices non ac risus. Sed dapibus, risus a mollis imperdiet, ipsum metus ultrices ante, nec cursus nisi metus ac enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus sed eros at maximus. Cras interdum iaculis diam, sollicitudin malesuada odio dignissim non. Nullam quis facilisis velit. Nam sit amet ligula consectetur, volutpat lorem nec, posuere mi. Praesent quis tempor risus, id pulvinar enim. Nulla nisi nunc, lacinia at malesuada et, vulputate a mauris. Etiam tempor volutpat ex. Nam gravida tempor pulvinar.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut malesuada dui. Aenean pharetra pretium vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel diam et enim aliquet ultrices non ac risus. Sed dapibus, risus a mollis imperdiet, ipsum metus ultrices ante, nec cursus nisi metus ac enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut maximus sed eros at maximus. Cras interdum iaculis diam, sollicitudin malesuada odio dignissim non. Nullam quis facilisis velit. Nam sit amet ligula consectetur, volutpat lorem nec, posuere mi. Praesent quis tempor risus, id pulvinar enim. Nulla nisi nunc, lacinia at malesuada et, vulputate a mauris. Etiam tempor volutpat ex. Nam gravida tempor pulvinar.
                <div className="wd-float-done"></div>
                <div className="wd-float-left wd-dimension-portrait wd-bg-color-yellow">
                    Yellow </div>
                <div className="wd-float-left wd-dimension-portrait wd-bg-color-blue wd-fg-color-white">
                    Blue </div>
                <div className="wd-float-left wd-dimension-portrait wd-bg-color-red">
                    Red </div>
                <img className="wd-float-right"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                <div className="wd-float-done"></div>
            </div>
        </div>
    );
}